[supervisord]
nodaemon=false
silent=true
user=autere

[program:autere]
directory=/home/autere
command=node /home/autere/dist-backend/backend/index.js
autostart=true
autorestart=true
stderr_logfile=/home/autere/log/autere.err.log
stdout_logfile=/home/autere/log/autere.out.log
