[supervisord]
nodaemon=false
silent=true
user=autere

[program:9router]
command=9router -n -t -l --skip-update
autostart=true
autorestart=true
stderr_logfile=/home/autere/log/9router.err.log
stdout_logfile=/home/autere/log/9router.out.log

[program:omniroute]
command=omniroute -q --no-color
autostart=false
autorestart=false
stderr_logfile=/home/autere/log/omniroute.err.log
stdout_logfile=/home/autere/log/omniroute.out.log

[program:autere]
directory=/home/autere/code/autere
command=./node_modules/.bin/tsx --max-old-space-size=8192 src/backend/index.ts --provider 9router
autostart=true
autorestart=true
stderr_logfile=/home/autere/log/autere.err.log
stdout_logfile=/home/autere/log/autere.out.log
